apiVersion: v1
kind: ServiceAccount
metadata:
  name: trailbrake-service-account
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: gke-workload@driverapp-2022.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: trailbrake-pod
  namespace: default
  labels:
    app: trailbrake-app
spec:
  serviceAccountName: trailbrake-service-account
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  containers:
  - image: asia-east1-docker.pkg.dev/driverapp-2022/trailbrake-api/trailbrake-api:latest
    name: trailbrake-pod
    imagePullPolicy: Always
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 100Mi
    #   limits:
    #     cpu: 200m
    #     memory: 500Mi
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: secrets
    env:
      - name: MONGO_DB_CERT
        value: /var/secrets/mongodb-cert
      - name: TOKEN_SECRET_KEY
        value: /var/secrets/token-secret-key
      - name: MONGO_DB_CONN
        value: /var/secrets/mongodb-conn
      - name: MONGO_DB_NAME
        value: /var/secrets/mongodb-name
      - name: JUDGE_URL
        value: http://trailbrake-judge-service
  volumes:
  - name: secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "trailbrake-secrets"
