apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: trailbrake-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/driverapp-2022/secrets/mongodb-cert/versions/latest"
        path: "mongodb-cert"
      - resourceName: "projects/driverapp-2022/secrets/token-secret-key/versions/latest"
        path: "token-secret-key"
      - resourceName: "projects/driverapp-2022/secrets/mongodb-conn/versions/latest"
        path: "mongodb-conn"
      - resourceName: "projects/driverapp-2022/secrets/mongodb-name/versions/latest"
        path: "mongodb-name"
