apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trailbrake-api
spec:
  template:
    spec:
      containers:
      - image: asia-east1-docker.pkg.dev/driverapp-2022/trailbrake-api/trailbrake-api:latest
        ports:
        - name: http1
          containerPort: 80
        volumeMounts:
        - mountPath: /var/secrets/mongodb-cert
          name: secrets-mongodb-cert
        env:
        - name: MONGO_DB_CERT
          value: /var/secrets/mongodb-cert
        - name: TOKEN_SECRET_KEY
          valueFrom: 
            secretKeyRef: 
              key: latest
              name: token-secret-key
        - name: MONGO_DB_CONN
          valueFrom: 
            secretKeyRef: 
              key: latest
              name: mongodb-conn
        - name: MONGO_DB_NAME
          valueFrom: 
            secretKeyRef: 
              key: latest
              name: mongodb-name
        - name: JUDGE_URL
          value: https://trailbrake-judge-f6muv3fwlq-de.a.run.app
      volumes:
      - name: secrets-mongodb-cert
        secret:
          items:
          - key : latest
            path: .
          secretName: mongodb-cert
